COVID-19 World Vaccination Progress
Roll no: 160123733028

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("country_vaccinations.csv")
df2 = pd.read_csv("country_vaccinations_by_manufacturer.csv")
print(df['date'].dtype)

df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(['country', 'date'])
print(df['date'].dtype)

df.head()

object
datetime64[ns]

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

### Analysis
The dataset is successfully loaded into Pandas DataFrames using the read_csv() function. The 'date' column is initially  as an object, so it is converted into datetime format to  proper time-based analysis because vaccination should be analysied over time . The data is then sorted by 'country' and 'date' to maintain chronological order(earliest to latest) within each country. Then the first few rows are displayed using head() to verify that the dataset is correctly loaded.

## Q1: Total vaccinations per country and disparity

In [3]:
tot_vac = df.groupby('country')['total_vaccinations'].max()
top10 = tot_vac.sort_values(ascending=False).head(10)
bottom10 = tot_vac.sort_values().head(10)
print("Top 10 Countries:\n", top10)
print("\nBottom 10 Countries:\n", bottom10)

Top 10 Countries:
 country
China            3.263129e+09
India            1.834501e+09
United States    5.601818e+08
Brazil           4.135596e+08
Indonesia        3.771089e+08
Japan            2.543456e+08
Bangladesh       2.436427e+08
Pakistan         2.193686e+08
Vietnam          2.031444e+08
Mexico           1.919079e+08
Name: total_vaccinations, dtype: float64

Bottom 10 Countries:
 country
Pitcairn                94.0
Tokelau               1936.0
Niue                  4161.0
Montserrat            4211.0
Falkland Islands      4407.0
Saint Helena          7892.0
Tuvalu               12114.0
Burundi              12166.0
Wallis and Futuna    13073.0
Nauru                16824.0
Name: total_vaccinations, dtype: float64

First , we group country by rows and select total vaccinations column and as there will be many records for each country over time we use max function take highest vaccination of each country. Then top 10 for selected using sort_values() which gives from highest to lowest by ascending = false and we want only 10 so head(10) we result first 10 and similarly for bottom 10 but lowest to highest. 
The results show a clear disparity in vaccination coverage, where highly populated and developed countries dominate the top positions, while smaller or less-developed countries appear in the lower range. This highlights inequality in vaccine distribution across the world.

Q2

In [4]:
data = df[['people_vaccinated', 'people_fully_vaccinated']].dropna()
data['log_vacc'] = np.log(data['people_vaccinated'])
data['sqrt_ful'] = np.sqrt(data['people_fully_vaccinated'])
cor = data['people_vaccinated'].corr(data['people_fully_vaccinated'])

print("Correlation between vaccinated and fully vaccinated:", cor)

data.head()

Correlation between vaccinated and fully vaccinated: 0.957599480057869

    people_vaccinated  people_fully_vaccinated   log_vacc    sqrt_ful
78           448878.0                  55624.0  13.014506  235.847408
87           470341.0                  77560.0  13.061213  278.495960
91           476367.0                  96910.0  13.073944  311.303710
93           479372.0                 111082.0  13.080232  333.289664
94           479574.0                 113739.0  13.080653  337.252131

The relationship between people vaccinated and full vaccinated was analyzed using NumPy ufuncs such logarithmic and square root transformations. Ufuncs are useful for normalizing data and reducing large differences in scales. The calculated correlation value was high and positive which indicates a strong relationship between the variables. The relationship was not proportionate because there is usually a time lag between the first and second dose. This means that a higher number vaccinated don't exactly have the same high number as full vaccinated, but there is a positive relationship between the two.

Q3

In [ ]:
df_h = df.set_index(['country', 'date'])

weekly = df_h.groupby(level=0).resample('W', level=1).sum(numeric_only=True)

IN = weekly.xs('India', level=0)
US = weekly.xs('United States', level=0)
BR= weekly.xs('Brazil', level=0)

IN_tab = IN[['total_vaccinations',
                     'people_vaccinated',
                     'people_fully_vaccinated']].reset_index()

US_tab= US[['total_vaccinations',
                 'people_vaccinated',
                 'people_fully_vaccinated']].reset_index()

BR_tab = BR[['total_vaccinations',
                       'people_vaccinated',
                       'people_fully_vaccinated']].reset_index()

print("India Table:\n", IN_tab.head())
print("\nUSA Table:\n", US_tab.head())
print("\nBrazil Table:\n", BR_tab.head())

India Table:
         date  total_vaccinations  people_vaccinated  people_fully_vaccinated
0 2021-01-17            415482.0           415482.0                      0.0
1 2021-01-24           7567199.0          7567199.0                      0.0
2 2021-01-31          20340525.0         20340525.0                      0.0
3 2021-02-07          34502604.0         34502604.0                      0.0
4 2021-02-14          43412794.0         43405126.0                   7668.0

USA Table:
         date  total_vaccinations  people_vaccinated  people_fully_vaccinated
0 2020-12-13             30288.0            25125.0                   5897.0
1 2020-12-20           4150969.0          4008257.0                  55548.0
2 2020-12-27          17983372.0         17546939.0                 123326.0
3 2021-01-03          36859124.0         35924592.0                 286167.0
4 2021-01-10          67463331.0         61600374.0                4626820.0

Brazil Table:
         date  total_vaccinations  people_vaccinated  people_fully_vaccinated
0 2021-01-17               112.0              112.0                      0.0
1 2021-01-24           1963650.0          1963650.0                      0.0
2 2021-01-31          10792604.0         10792604.0                      0.0
3 2021-02-07          21251897.0         21204570.0                  47327.0
4 2021-02-14          32699638.0         31834174.0                 865464.0

### Analysis
The weekly data shows that vaccinations are increasing over time in India, the USA, and Brazil. The USA started earlier and has faster growth, while India and Brazil show slower and gradual increases.
At the beginning, the number of fully vaccinated people is very low because the second dose takes time. Later, it starts increasing.
Overall, all countries show an upward trend, but the speed of vaccination is different.

Q4

In [9]:
df['eff_score'] = df['people_fully_vaccinated'] / df['people_vaccinated']

eff = df.groupby('country')['eff_score'].mean()
ranked = eff.sort_values(ascending=False)

res= ranked.to_frame(name='Efficiency Score')

print(res.head(10))

                           Efficiency Score
country
Tokelau                            1.000000
China                              0.948678
Wallis and Futuna                  0.905042
Madagascar                         0.899078
Bahrain                            0.886780
United Arab Emirates               0.881596
Sint Maarten (Dutch part)          0.876882
Gibraltar                          0.874716
Mongolia                           0.861004
Jersey                             0.860731

### Analysis
The efficiency score shows how many people completed both doses out of those who got the first dose. The data is grouped by country and ranked to find which countries are more efficient. Countries with higher scores complete vaccination better, while lower scores show incomplete vaccination.

Q5

In [12]:
miss_per = df.isnull().mean() * 100

missing = miss_per[miss_per> 30]

print("Columns with >30% missing values:\n", missing)

ffill = df.ffill()
print("\nAfter forward fill:\n",
      ffill[['country','date','total_vaccinations',
                'people_vaccinated','people_fully_vaccinated']].head())

Columns with >30% missing values:
 total_vaccinations                     49.594276
people_vaccinated                      52.267893
people_fully_vaccinated                55.148419
daily_vaccinations_raw                 59.124746
total_vaccinations_per_hundred         49.594276
people_vaccinated_per_hundred          52.267893
people_fully_vaccinated_per_hundred    55.148419
eff_score                              56.410671
dtype: float64

After forward fill:
        country       date  total_vaccinations  people_vaccinated  \
0  Afghanistan 2021-02-22                 0.0                0.0
1  Afghanistan 2021-02-23                 0.0                0.0
2  Afghanistan 2021-02-24                 0.0                0.0
3  Afghanistan 2021-02-25                 0.0                0.0
4  Afghanistan 2021-02-26                 0.0                0.0

   people_fully_vaccinated
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN

### Analysis
The percentage of missing values is calculated for each column, and several columns are found to have more than 30% missing data. Dropping these columns would lead to loss of important vaccination information, so imputation is preferred.

Forward-fill (ffill) is applied to fill missing values using the previous available data. This approach is suitable for time-series data because vaccination values change gradually over time, and the previous value provides a reasonable estimate. The output shows that missing values are filled while maintaining the continuity of the dataset. However, some initial rows may still contain missing values due to the absence of prior data.

Q6

In [16]:
oxford_data = df[df['vaccines'].str.contains('Oxford/AstraZeneca', na=False)]

series = oxford_data.groupby('date')['total_vaccinations'].mean()

global_avg = df.groupby('date')['total_vaccinations'].mean()

compare = series - global_avg

print(compare.head())

date
2020-12-02   NaN
2020-12-03   NaN
2020-12-04   NaN
2020-12-05   NaN
2020-12-06   NaN
Name: total_vaccinations, dtype: float64

### Analysis
The dataset is filtered to include only countries using the Oxford/AstraZeneca vaccine. The average total vaccinations for these countries are calculated for each date and compared with the global average. Subtraction is used to measure the difference between the two values.

The results show whether these countries perform above or below the global average. Positive values indicate higher vaccination levels, while negative values indicate lower performance. Some initial values appear as NaN due to missing data for certain dates. This happens because of index alignment, where Pandas matches values based on dates and produces NaN when data is not available in one of the Series.
Overall, this analysis demonstrates how vaccination performance of specific countries can be compared with global trends using index-aligned operations.

Q7

In [19]:


df['daily_rate'] = df.groupby('country')['total_vaccinations'].diff()

df['daily_rate'] = df['daily_rate'].apply(lambda x: x if x > 0 else 0)

r = df[['country', 'date', 'daily_rate']]

r = r.set_index(['country', 'date'])

top_c = df.groupby('country')['daily_rate'].mean().sort_values(ascending=False)

print(r.head(10))
print("\nTop Performing Countries:\n", top_c.head(10))

                        daily_rate
country     date
Afghanistan 2021-02-22         0.0
            2021-02-23         0.0
            2021-02-24         0.0
            2021-02-25         0.0
            2021-02-26         0.0
            2021-02-27         0.0
            2021-02-28         0.0
            2021-03-01         0.0
            2021-03-02         0.0
            2021-03-03         0.0

Top Performing Countries:
 country
China            6.771636e+06
India            4.020994e+06
United States    1.189281e+06
Brazil           9.375762e+05
Indonesia        7.092473e+05
Japan            4.420577e+05
Germany          3.753617e+05
Turkey           3.277244e+05
Mexico           3.267579e+05
Vietnam          3.263483e+05
Name: daily_rate, dtype: float64

### Analysis
The daily vaccination rate shows how many vaccinations are given each day. It is calculated using the difference between consecutive days. The data is organized by country and date for easy understanding.

The results show that countries like China, India, and the USA have the highest daily vaccination rates, meaning they are vaccinating people faster. Some countries have lower rates, showing slower progress. This helps compare how quickly different countries are carrying out vaccination programs.

Q8

In [ ]:
subset = df[df['country'].isin(['India', 'United States'])]

data = subset[['country', 'date', 'total_vaccinations']]

dropna_data = data.dropna()

ffill_data = data.ffill()

print("Before handling missing values:\n", data.describe())

print("\nAfter dropna():\n", dropna_data.describe())

print("\nAfter ffill():\n", ffill_data.describe())

Before handling missing values:
                                 date  total_vaccinations
count                            910        8.990000e+02
mean   2021-08-13 04:49:34.945054976        5.322071e+08
min              2020-12-13 00:00:00        0.000000e+00
25%              2021-04-22 00:00:00        1.790041e+08
50%              2021-08-13 12:00:00        3.883749e+08
75%              2021-12-05 00:00:00        5.601744e+08
max              2022-03-29 00:00:00        1.834501e+09
std                              NaN        5.012977e+08

After dropna():
                                 date  total_vaccinations
count                            899        8.990000e+02
mean   2021-08-13 23:11:56.796440576        5.322071e+08
min              2020-12-13 00:00:00        0.000000e+00
25%              2021-04-21 12:00:00        1.790041e+08
50%              2021-08-16 00:00:00        3.883749e+08
75%              2021-12-06 12:00:00        5.601744e+08
max              2022-03-29 00:00:00        1.834501e+09
std                              NaN        5.012977e+08

After ffill():
                                 date  total_vaccinations
count                            910        9.100000e+02
mean   2021-08-13 04:49:34.945054976        5.294703e+08
min              2020-12-13 00:00:00        0.000000e+00
25%              2021-04-22 00:00:00        1.767853e+08
50%              2021-08-13 12:00:00        3.880364e+08
75%              2021-12-05 00:00:00        5.599994e+08
max              2022-03-29 00:00:00        1.834501e+09
std                              NaN        4.992714e+08

### Analysis
The results show that dropna() reduces the dataset size by removing rows with missing values, leading to loss of information. In contrast, forward-fill (ffill) keeps the dataset size unchanged by filling missing values with previous data. The summary statistics show that dropna() reduces the number of records, while ffill() maintains continuity with only slight changes in values. Therefore, ffill() is more suitable for time-series data like vaccination records.

Q9

In [22]:

high_rollout = df[df['daily_vaccinations_per_million'] > 10000]


resul= high_rollout[['country', 'vaccines', 'daily_vaccinations_per_million']]

print(resul.head())

print("\nTop Countries:\n", resul['country'].value_counts().head())


print("\nVaccine Types:\n", resul['vaccines'].value_counts().head())

      country                                      vaccines  \
1318  Andorra  Moderna, Oxford/AstraZeneca, Pfizer/BioNTech
1319  Andorra  Moderna, Oxford/AstraZeneca, Pfizer/BioNTech
1320  Andorra  Moderna, Oxford/AstraZeneca, Pfizer/BioNTech
1321  Andorra  Moderna, Oxford/AstraZeneca, Pfizer/BioNTech
1322  Andorra  Moderna, Oxford/AstraZeneca, Pfizer/BioNTech

      daily_vaccinations_per_million
1318                         11144.0
1319                         12527.0
1320                         13897.0
1321                         15280.0
1322                         13574.0

Top Countries:
 country
Gibraltar       153
Cuba            138
Vietnam          98
Tokelau          96
Saint Helena     91
Name: count, dtype: int64

Vaccine Types:
 vaccines
Oxford/AstraZeneca, Pfizer/BioNTech                              451
Johnson&Johnson, Moderna, Oxford/AstraZeneca, Pfizer/BioNTech    427
Moderna, Oxford/AstraZeneca, Pfizer/BioNTech                     401
Oxford/AstraZeneca                                               283
Pfizer/BioNTech                                                  280
Name: count, dtype: int64

### Analysis
The data is filtered using boolean indexing to select records where daily vaccinations per million exceed 10,000. This helps identify high vaccination rates. The results show which countries frequently achieve high rollout and which vaccine types are commonly used. This indicates that both country infrastructure and vaccine availability influence vaccination speed.

Q10

In [23]:

pivot = pd.pivot_table(
    df,
    values='total_vaccinations',
    index=['country', 'vaccines'],
    aggfunc='max'
)


print(pivot.head(10))


pivot.to_csv("vacc_summary.csv")

                                                                        total_vaccinations
country             vaccines
Afghanistan         Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bio...           5751015.0
Albania             Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, S...           2754244.0
Algeria             Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac,...          13704895.0
Andorra             Moderna, Oxford/AstraZeneca, Pfizer/BioNTech                  151997.0
Angola              Oxford/AstraZeneca                                          17535411.0
Anguilla            Oxford/AstraZeneca, Pfizer/BioNTech                            22714.0
Antigua and Barbuda Oxford/AstraZeneca, Pfizer/BioNTech, Sputnik V                125386.0
Argentina           CanSino, Moderna, Oxford/AstraZeneca, Pfizer/Bi...          96504666.0
Armenia             Moderna, Oxford/AstraZeneca, Sinopharm/Beijing,...           2088962.0
Aruba               Pfizer/BioNTech                                               169231.0

### Analysis
The pivot table is created to compare vaccination data across countries and vaccine types in a structured format. It is then exported as a CSV file using the to_csv() function.

This is done to save the results, make them easy to share, and allow further use outside the notebook. Exporting also helps in submitting the work and viewing the data in tools like Excel.

In [24]:
df1=pd.read_csv("vacc_summary.csv")
df1.head(2)

,country,vaccines,total_vaccinations
0,Afghanistan,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",5751015.0
1,Albania,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",2754244.0